### ISSUE TITLE
Import PropTypes from prop-types to remove warning in React ^15.5.0

### ISSUE THREAD

**Issue by erasmo-marin** [zippytech/react-notify-resize#1]
Now react 15.5.0 ships the prop-types in a different package. This causes a warning.

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by zpytchrb** [comment]
See https://github.com/zippytech/react-notify-resize/releases/tag/v3.0.0
